name: terraform-apply

on:
  push:
    branches:
      - main

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2.1.6
        with:
          workload_identity_provider: 'projects/585501833219/locations/global/workloadIdentityPools/github-action-sandbox-ldy/providers/github-provider'
          project_id: ${{ env.PROJECT_ID }}
          service_account: 'tf-sa-635@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'
          create_credentials_file: true
          access_token_lifetime: 3600
      - run: terraform init
      - run: terraform test
      - run: terraform plan -lock=false
      - run: terraform apply -lock=false -auto-approve
