name: terraform-plan

on:
  pull_request:

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2.1.5
        with:
          workload_identity_provider: 'projects/585501833219/locations/global/workloadIdentityPools/github-action-sandbox-ldy/providers/github-provider'
          project_id: ${{ env.PROJECT_ID }}
          service_account: 'tf-sa-635@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'
          create_credentials_file: true
          access_token_lifetime: 3600
      - run: terraform init
      - run: terraform test
      - run: terraform apply -target data.google_service_account.get_sa -target google_service_account.create_account -lock=false -auto-approve
      - run: terraform plan -lock=false -out terraform.plan
      # generate plain output
      - run: terraform show -no-color terraform.plan > terraform.text
      # generate json output
      - run: terraform show -json terraform.plan > terraform.json
      - uses: ahmadnassri/action-terraform-report@v4
        with:
          # tell the action the plan outputs
          terraform-text: ${{ github.workspace }}/terraform.text
          terraform-json: ${{ github.workspace }}/terraform.json
          remove-stale-reports: true
